language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn
  - yarn deploy-presentation
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: presentation/build
  on:
    branch: master